---
title: "Wrapping, Unwrapping and Converting In Dynamo"
subTitle: "Thuáº­t Ngá»¯ Viáº¿t MÃ£ Trong Dynamo"
category: dynamo
cover: cover.png
---

ChÃ o má»«ng cÃ¡c bÃ¡c Ä‘Ã£ ghÃ© thÄƒm blog cá»§a mÃ¬nh.ğŸ˜„

### Má»¥c Ä‘Ã­ch

- BÃ i nÃ y Ä‘Æ°á»£c viáº¿t ra vá»›i má»¥c Ä‘Ã­ch tá»•ng há»£p láº¡i cÃ¡c tá»« khoÃ¡ mÃ  cÃ¡c anh em hay dÃ¹ng trung láº­p trÃ¬nh viáº¿t mÃ£ vá»›i `Python` hoáº·c `C#`.

### Unwrapping 

Unwrapping : Hiá»ƒu Ä‘Æ¡n giáº£n nháº¥t lÃ  gÃ¬ , chÃ­nh lÃ  Ä‘Ã²i em Dynamo má»Ÿ cÃ¡i kháº©u trang ra cho anh Revit coi máº¯t vÃ  xem Ä‘Æ°á»£c, biáº¿t Ä‘Æ°á»£c em nÃ³ lÃ  con nhÃ  ai, cÃ³ vá»£ hay chÆ°a cÃ³ vá»£.Rá»“i sau Ä‘Ã³ má»›i muá»‘n lÃ m gÃ¬ thÃ¬ lÃ m.ğŸ˜

CÃº PhÃ¡p : 
- Viáº¿t vá»›i má»™t Funtion Ä‘á»ƒ sá»­ dá»¥ng láº¡i
```
defÂ Unwrap(item):
Â Â Â Â returnÂ UnwrapElement(item)
```
- Viáº¿t vá»›i má»™t dÃ²ng Ä‘Æ¡n
```
Input = UnwrapElement( IN[0] )
```
Lá»—i náº¿u thiáº¿u :
Náº¿u mÃ¬nh khÃ´ng sá»­ dá»¥ng **UnwrapElement** thÃ¬ Ä‘a sá»‘ lÃ  sáº½ bÃ¡o lá»—i thiáº¿u thuá»™c tÃ­nh, Ä‘áº¡i loáº¡i nhÆ° tháº¿ nÃ y :

![](pic/Screendsdashot_ssdsdsdÆ°1.png)

VÃ­ dá»¥ láº¥y vá» type_parameter tá»« má»™t Äá»‘i tÆ°á»£ng bÃªn ngoÃ i : 
```
group = UnwrapElement(IN[0])
group_type_id = group.GetTypeId()
group_type = doc.GetElement(group_type_id)
type_parameter = group_type.LookupParameter("Mark")
OUT = type_parameter
```
### Wrapping
ThÃ´ng thÆ°á»ng sáº½ cÃ³ cÃ¡c mÃ£ ta hay nhÃ¬n tháº¥y nhÆ° :
- InternalElement  : Hiá»ƒu Ä‘Æ¡n giáº£n lÃ  trong lá»›p Revit.Elements nÃ³ Ä‘Ã£ tráº£ vá» má»™t **wrapped** trong **Dynamo**, vÃ¬ váº­y ta cáº§n pháº£i cháº¡y lá»‡nh nÃ y Ä‘á»ƒ cÃ³ quyá»n truy cáº­p vÃ o cÃ¡c Ä‘á»‘i tÆ°á»£ng.
- ToDSType(bool) : Äá»ƒ thÃ´ng bÃ¡o ráº±ng tui vá»«a láº¥y má»™t Ä‘á»‘i tÆ°á»£ng trong revit vÃ  quÄƒng vÃ o **Dynamo** Ä‘Ã¢y.Náº¿u Ä‘á»ƒ True thÃ¬ Ä‘á»“ng Ã½ cÃ²n ngÆ°á»£c láº¡i thÃ¬ khÃ´ng .

VÃ­ dá»¥ vá» láº¥y ElementId :
```
/// <summary>
        /// 
        /// </summary>
        /// <param name="element"></param>
        /// <returns></returns>
        public static ElementId GetId(Element element)
        {
            Autodesk.Revit.DB.Element UnwrapElement = element.InternalElement;

            ElementId unWrapElementId = UnwrapElement.Id;
            return unWrapElementId;
        }

```

VÃ­ dá»¥ táº¡o tÆ°á»ng :
```
 var walls = new List<Revit.Elements.Wall>();
  //elements creation and modification has to be inside of a transaction
  TransactionManager.Instance.EnsureInTransaction(Document);
  foreach (var curve in lines)
  {
    // use the Revit Wall.Create API to make a new wall element
      var wall = Autodesk.Revit.DB.Wall.Create(
        Document, // note the required reference to the Revid Document
        curve.ToRevitType(), // also note we need to convert Dynamo curves to Revit types
        wallType.InternalElement.Id, // Revit elements returned from Dynamo are wrapped, so we need to access the internal element directly
        level.InternalElement.Id, 
        height, 
        0.0, 
        false, 
        false);
      walls.Add(wall.ToDSType(false) as Revit.Elements.Wall); // notice we need to wrap Revit elements back so they can be used in Dynamo
  }

```
### Converting
Chuyá»ƒn Ä‘á»•i qua chuyá»ƒn Ä‘á»•i láº¡i tá»« Ä‘á»‘i tÆ°á»£ng Revit sang Dynamo vÃ  ngÆ°á»£c láº¡i , má»™t ngÃ y nÃ o Ä‘Ã³ nÃ³ chuyá»ƒn qua chá»— khÃ¡c thÃ¬ cÅ©ng sáº½ cÃ³ thÃªm vÃ i cÃ¡i ná»¯a, Ä‘Æ¡n giáº£n lÃ  váº­y 
- Tá»« Revit Sang Dynamo 
```
//Elements
Element.ToDSType(bool);
//Geometry
XYZ.ToPoint() > Point
XYZ.ToVector() > Vector
Point.ToProtoType() > Point
List<XYZ>.ToPoints() > List<Point>
UV.ToProtoType() > UV
Curve.ToProtoType() > Curve
CurveArray.ToProtoType() > PolyCurve
PolyLine.ToProtoType() > PolyCurve
Plane.ToPlane() > Plane
Solid.ToProtoType() > Solid
Mesh.ToProtoType() > Mesh
IEnumerable<Mesh>.ToProtoType() > Mesh[]
Face.ToProtoType() > IEnumerable<Surface>
Transform.ToCoordinateSystem() > CoordinateSystem
BoundingBoxXYZ.ToProtoType() > BoundingBox

```
- Tá»« Dynamo sang Revit
```
//Elements
Element.InternalElement
//Geometry
Point.ToRevitType() > XYZ
Vector.ToRevitType() > XYZ
Plane.ToPlane() > Plane
List<Point>.ToXyzs() > List<XYZ>
Curve.ToRevitType() > Curve
PolyCurve.ToRevitType() > CurveLoop
Surface.ToRevitType() > IList<GeometryObject>
Solid.ToRevitType() > IList<GeometryObject>
Mesh.ToRevitType() > IList<GeometryObject>
CoordinateSystem.ToTransform() > Transform
CoordinateSystem.ToRevitBoundingBox() > BoundingBoxXYZ
BoundingBox.ToRevitType() > BoundingBoxXYZ

```

### Tá»•ng káº¿t
HÃ´m nay lÃ  má»™t ngÃ y Ä‘áº¹p trá»i, bá»‡nh dá»‹ch Corona Ä‘ang hoÃ nh hÃ nh, cÃ¡c bÃ¡c hÃ£y báº£o trá»ng sá»©c khoáº» vÃ  trÃ¡nh ra Ä‘Æ°á»ng tiáº¿p xÃºc, rá»­a tay thÆ°á»ng xuyÃªn nhÃ©.CÃ¡m Æ¡n cÃ¡c bÃ¡c Ä‘Ã£ ghÃ© thÄƒm blog cá»§a mÃ¬nh .Náº¿u cÃ³ tháº¯c máº¯c hoáº·c gÃ³p Ã½ bá»• sung bÃ i viáº¿t , cÃ¡c bÃ¡c hÃ£y Ä‘á»ƒ láº¡i bÃ¬nh luáº­n bÃªn dÆ°á»›i bÃ i viáº¿t nhÃ©.

### Tham kháº£o :

<a href="https://github.com/StudioLE/DynamoDevelopment-London-Hackathon-2019/blob/master/03-ZeroTouch/04-RevitNodeDevelopment.md" target="_blank">DynamoDevelopment</a> 

<a href="https://developer.dynamobim.org/" target="_blank">Dynamo Developer</a> 
